//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetWebServeurV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class episode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public episode()
        {
            this.user = new HashSet<user>();
        }
    
        public int id { get; set; }
        public int season_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string imdb { get; set; }
        public Nullable<double> imdbrating { get; set; }
        public int number { get; set; }
    
        public virtual season season { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user { get; set; }
    }
}
