//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetWebServeurV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class external_rating
    {
        public int id { get; set; }
        public int series_id { get; set; }
        public int source_id { get; set; }
        public string value { get; set; }
        public Nullable<int> votes { get; set; }
    
        public virtual series series { get; set; }
        public virtual external_rating_source external_rating_source { get; set; }
    }
}
